Free various struct membuffer in different functions
Subsurface-divelog/subsurface pull request #1068
Opened 2018-01-22 20:14 UTC by sfuchs79

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

@neolit123 correctly highlighted that I introduced a struct membuffer in my code and forgot to free it.
While learning how to fix it correctly I think I found some more missing free_buffer().

But please check this carefully because maybe I misunderstood s.th.!

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

@neolit123

2018-01-22 20:51 UTC, neolit123 requested changes
thanks for the PR, actually some of the changes can cause some trouble, thus i've added a review for these. requesting a review from others too - @mturkia @dirkhh

2018-01-22 20:51 UTC, neolit123 commented on core/save-git.c
> +	free_buffer(&buf);
this is a double `free_buffer()`. look at `blob_insert()` - it already calls `free_buffer()`.
it's not ideal that the ownership is transferred to `blob_insert()`, too.

2018-01-22 20:51 UTC, neolit123 commented on core/linux.c
> +		free_buffer(&mb);
this one looks good.

2018-01-22 20:51 UTC, neolit123 commented on core/save-git.c
> +	free_buffer(&buf);
double `free_buffer()`. there is a `blob_insert()` call above.

2018-01-22 20:51 UTC, neolit123 commented on core/save-git.c
> +	free_buffer(&b);
double `free_buffer()`. there is a `blob_insert()` call above.

2018-01-22 20:51 UTC, neolit123 commented on core/save-git.c
> +	free_buffer(&dirname);
this one looks good.

2018-01-22 20:51 UTC, neolit123 commented on core/save-git.c
> +		free_buffer(&b);
double `free_buffer()`. there is a `blob_insert()` call above.

2018-01-22 20:51 UTC, neolit123 commented on core/save-git.c
> +		free_buffer(&site_file_name);
this one looks good.

2018-01-22 20:51 UTC, neolit123 commented on desktop-widgets/subsurfacewebservices.cpp
> +		free_buffer(&mb);
the `mb` variable itself is allocated on the stack.
the above call already handles the memory de-allocation - `free((void *)membuf);`
but i would remove the `free((void *)membuf);` line and leave the line you've added `free_buffer(&mb);`

2018-01-22 20:51 UTC, neolit123 commented on profile-widget/diveeventitem.cpp
> +		free_buffer(&mb);
this is a nitpick.
i would reduce the scope of the `free_buffer(&mb);` here and place it bellow the `name += QString::fromUtf8(mb.buffer, mb.len);` line. it is relevant only if the `put_format()` call above succeeds.

2018-01-23 06:09 UTC, sfuchs79 commented
Updates done. Please review again!

2018-01-23 23:36 UTC, neolit123 approved these changes
lgtm, thanks. someone needs to double check.

2018-01-27 16:14 UTC, dirkhh commented
I don't think my brain is clear enough to do a valid code review. Hopefully I'll feel better by Monday. This flu sucks...

2018-02-02 19:29 UTC, dirkhh commented
ok, lgtm

2018-02-02 19:29 UTC, merged