Do not remove seconds from duration input field
Subsurface-divelog/subsurface pull request #1094
Opened 2018-02-04 19:33 UTC by Schwaneberg

### Describe the pull request:

- [ ] Bug fix
- [X] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
If you enter a dive duration manually, the cell renderer cuts the seconds away when the changes are saved. The rendering of the cell is done at two places in the code, so I think it is cleaner to add a dedicated method for it. 
I added the helper "render_seconds_to_string" as a counterpart to "parseDurationToSeconds". The helper keeps the seconds if not null.

### Changes made:
1) Method render_seconds_to_string(int seconds) was added to qthelper. E.g., it converts 3700 to "1:10" and 3730 to "1:10:30".
2) The new method is used to render the string in the duration field of the add dive ui.

### Related issues:
#554

2018-02-04 20:52 UTC, dirkhh requested changes
Would you mind adding a CHANGELOG entry?

2018-02-04 20:56 UTC, Schwaneberg commented
The changelog already contains the item "Small UI fixes". I would say that this is sufficient for such a small change. Okay?

2018-02-04 21:39 UTC, dirkhh commented
Always depends on the level of detail that we want :-)
I'll merge @neolit123 's much more detailed changelog in a moment - and with that another comment for this one might be worth while, but I can add that myself as well.

2018-02-04 21:39 UTC, dirkhh approved these changes

2018-02-04 21:40 UTC, merged

2018-02-05 07:21 UTC, Schwaneberg commented
Thank you, Dirk!