Add support for smtk-import on travis-ci
Subsurface-divelog/subsurface pull request #1126
Opened 2018-02-19 22:32 UTC by salvadorcunat

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [X] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Add smarttrak import tool to continuous build. This way, if any change breaks the importer, it won't go unnoticed.
Patches 1 and 2 are the important part of the addition.  3, 4 and 5 should be considered optional and only apply if we want to upload a windows installer and an appimage to subsurface's repo.

Please, note that building the tool under mxe environment needs some precompiled static libraries.  I've built my own file with them and the script dowloads this file from my dropbox.
If you are concerned by this, feel free to build the static libraries and modify the script accordingly. 

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2018-02-21 11:27 UTC, neolit123 approved these changes
i think the change looks right and it's a complete one, but it would be best if @dirkhh has a look too as he understands the travis builds the best.

thanks!

2018-02-24 19:48 UTC, dirkhh requested changes
This looks useful.
Can you please "sign-off" these commits so we can merge them?

2018-02-24 21:13 UTC, salvadorcunat commented
Signed.
Best regards.

2018-02-24 21:41 UTC, dirkhh approved these changes

2018-02-24 21:42 UTC, merged