RFC:  Showing po2 graphs with pscr dives using active o2 monitoring
Subsurface-divelog/subsurface pull request #1143
Opened 2018-02-28 09:23 UTC by willemferguson

This is a first step to provide po2 values for pscr dives where
there is active po2 monitoring using a dive computer. The present
implementation is based on using a Petrel 2 with external o2
sensor. Currently, the display of pscr dives shows a computed po2
graph, based on a steady state approximation. See image below

![existing profile](https://user-images.githubusercontent.com/5078706/36778665-176250dc-1c76-11e8-8448-d5b9741297cd.jpg)

There is no provision for the display of pscr dives that use an oxygen
sensor to monitor po2. There are a few issues or question that I have
numbered in the notes below.

**What is new:**
This PR implements display of po2 graph based on an external oxygen
sensor. See image below:

![new_po2](https://user-images.githubusercontent.com/5078706/36778694-33672834-1c76-11e8-85bb-f32e7ca5c0f8.jpg)

In addition, the CCR setpoint preference is used to show the normal
OC po2 values for the dive. Just as the setpoint is the reference value against which
ccr dive po2 values are judged, so the OC po2 value is the one against which pscr
po2 values are judged. they have an exact analogous use in dive interpretation.
Consequently, if one checks the box "Show setpoints when viewing po2" in the
Preferences tab, the OC po2 values are shown in red for pscr profiles. See image below:

![setpoint](https://user-images.githubusercontent.com/5078706/36778900-d340991c-1c76-11e8-80c0-130c9df6b067.jpg)

ISSUE 1. I am not sure how the divecomputer->no_o2sensors information gets into
Subsurface. In this case I scan sample->o2sensor[0] and if any positive values are found
I set the divecomputer->no_o2sensors to 1. I am not convinced this is the most
efficient way of doing this.

ISSUE 2: In function fill_pressures (dive.c) I fill the setpoint array to the
OC po2 values. but I cannot find an easy way to access the fraction of O2 in the
gasmix. Therefore I added an additional parameter to that function header. This
propagated into the calls to this function in deco.c and plannernotes.c. My solution
does not appear particularly elegant.

ISSUE 3: Currently the po2 graph for scr dives with o2 sensors only covers the period
when the diver is on the loop (part of dive between red flags on dive profile images above).
One would like
to extend this by adding the OC po2 values for parts of the dive that are off the loop
(typically at the start and at the end of the dive). This requires that one can see the
events for going onto the loop and going off the loop. I do not think this works for the
Petrel 2. One can fix this with a piece of duct tape by inferring these events from the po2
sensor values (po2 is not recorder when off the loop). There must be a much better
way of doing this. Therefore I do not have a clear idea of how to add this this to the current
implementation.

Any comments or suggestions are extremely valuable.

Signed-off-by: Willem Ferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

@atdotde 
@sfuchs79 
@glance-

2018-02-28 09:42 UTC, janmulder commented on core/profile.c
> +		}
New code, but commented out ... not sure you want this, or is an unintentional error.

2018-02-28 10:02 UTC, willemferguson commented
This is my fudge for switching between a dive with and without external po2 measurement. I will get rid of that. The PR below corrects that.

2018-03-01 19:50 UTC, neolit123 requested changes
added some small style related comments.

2018-03-01 19:50 UTC, neolit123 commented on core/dive.c
> +			} else {           /* else, the steady state approximation should be good enough */
we need to have some sort of consistency about the line comments.

please use `//` for single line comments. we seem to be mixing these in the `dive.c` file. but `//` is the c99 way for single line comments.

also please only use a single space after the code ends on a line, for example this is good:
```
if (no_o2sensors) { // If O2 is being monitored use the provided value`
```
this isn't:
```
if (no_o2sensors) {                    // If O2 is being monitored use the provided value`
```

there is no point to align the line comments.
but if for *some* reason comments need alignment on the right of code, this should be done with spaces and not tabs.

2018-03-01 19:50 UTC, neolit123 commented on core/dive.c
> +			if (no_o2sensors) {  // If O2 is being monitored use the provided value
no need for the braces `{ }` around single lined `if / then / else`.

2018-03-01 19:50 UTC, neolit123 commented on core/profile.c
> +			if ((dc->no_o2sensors == 0) && (sample->o2sensor[0].mbar)) // We assume only a single O2 sensor
it's ok to change the above to:
`if (dc->no_o2sensors == 0 && sample->o2sensor[0].mbar)`

2018-03-01 19:50 UTC, neolit123 commented on core/profile.c
> +			entry->o2pressure.mbar = MIN(o2pressure.mbar, amb_pressure.mbar);
i think the above should be indented one more tab to the right?

2018-03-01 19:50 UTC, neolit123 commented on core/profile.c
> +		else if (dc->divemode == CCR) {
please move the `else if` on the previous line.

2018-03-01 19:50 UTC, neolit123 commented on profile-widget/profilewidget2.cpp
> +		ccrsensor1GasItem->setVisible((currentdc->divemode == PSCR) && (currentdc->no_o2sensors));
the above two lines can be changed to:
```
o2SetpointGasItem->setVisible(currentdc->divemode == PSCR && currentdc->no_o2sensors);
ccrsensor1GasItem->setVisible(currentdc->divemode == PSCR && currentdc->no_o2sensors);
```

2018-03-02 12:43 UTC, neolit123 commented
thank you for the update @willemferguson!
sadly, github does not have commit message reviews.

here are a couple of notes about the commit message with hopes that these would be helpful to you to improve the commit messages. i'm far from an expert in English, though.

**title:**
`Showing po2 graphs with pscr dives using active o2 monitoring`

i would use present tense and capitalize chemical formulas and abbreviations:
`Show PO2 graphs with PSCR dives using active O2 monitoring`

present tense is used so that the commit message describes what the commit does as if it isn't applied yet.

**commit body:**
```
This is a first step to provide po2 values for pscr dives where
there is active po2 monitoring using a dive computer. The present
implementation is based on using a Petrel 2 with external o2
sensor. I provide much more information in the accompanying notes.
```

i would capitalize chemical formulas and abbreviations. de-personalize the last sentence like academic papers do:
`More information is provided in the accompanying notes.`
(notice how how the verb is now `is` (to be) while` provided` is now the adjective)

```
Edit 1: Remove some redundant code from core/profile.c
```
remove `Edit X:` - we do not track edit history in commit messages.
probably elaborate a location where the code cleanup happens.

```
Edit 2: Changed some of the c syntax requested by @neolit123. This
        included the structure of comments and the way if statements
        are used.
```
the paragraph can be removed - we do not track edit history in commit messages.

2018-03-02 13:22 UTC, willemferguson commented
@neolit123, would you like me to edit the commit message? Kind regards, willem

2018-03-02 13:36 UTC, neolit123 commented
@willemferguson  yes, please. amend the commit.

2018-03-02 15:14 UTC, neolit123 approved these changes

2018-03-02 15:15 UTC, neolit123 commented
thanks, let's wait to see if the others have any comments on this.

2018-03-02 15:31 UTC, glance- commented
It feels like you're making the logic way more complex than it needs to be.

For pscr with o2 sensors the math is just the same as for ccr's with o2-sensors. The only difference is that the o2 sensor is telling you how much lower your o2 is than the "diluent" instead of higher in the ccr case.

Just verify that the math doesn't make the asumption that o2 > dil-o2 and your good to use the same code, without duplicating it.

2018-03-02 16:32 UTC, dirkhh commented
@glance- your comment sounds like a NAK on this approach, am I reading this correctly?

2018-03-02 17:04 UTC, willemferguson commented
There is a choice here, either the CCR code needs quite bit of reworking to make it work both for CCR and SCR, or the SCR code can be separate. In terms of maintainability, I prefer the separate approach. There are 3 reasons:
1) The setpoint information needs to populated with non-setpoint data. We cannot use the CCR setpoint information.
2) There needs to be a second round of implementation where the pO2 data are adapted, depending on whether the diver is on an OC pert or a CC part of the dive. For SCR, OC diving is always part of the dive. That means part of the pO2 profile needs to be replaced with OC pO2 data.
3) SCR dives can be with or without active external O2 monitoring, different from CCR. Without monitoring, SCR is much closer akin to OC diving.
Because of this, the CCR code will probably need quite bit of adaptation. For reasons above my personal preference is to keep the SCR code separate.

2018-03-02 18:48 UTC, glance- commented
Setpoint is setpoint, and shouldn't be abused for something else. It might be useful to you, but its just odd and hard do understand for everybody else. If you would like to have a reference "OC" po2, it shouldn't be entangled with setpoint handling.

For a PSCR with a po2 monitor it doesn't matter if your "CCR" or "OC". Just look at the po2 and the "dil" and your done. It doesn't matter if your 100% CCR or 100% OC, as long as you know the po2.

PSCR without po2 monitor is a different thing, but only different in the sense that you need to calculate the po2, and after that everything is the same.

The switch from CCR/PSCR to OC should be modeled as a bailout, which works just the same from CCR to OC and from PSCR to OC.

I think this code is way more complicated than it needs to be.

2018-03-02 18:59 UTC, glance- commented
I don't have any sane test data, and i'm a bit to tired to make it up right now, but the only change i see needed is to add a case about SCR in core/profile.c:586 , so the o2sensor values gets populated, and i think most of the bits will just fall in place. Or maybe even a divemode == CCR || divemode == PSCR.

2018-03-02 19:36 UTC, willemferguson commented
Please see my questions at the top of the PR. Where is dc->no_o2sensors set?

2018-03-02 20:20 UTC, glance- commented
core/libdivecomputer.c:396

2018-03-05 11:59 UTC, willemferguson commented
Comment on the PR above:
In profile.c (line 592), the dc->no_o2sensors is currently hard-forced to 1 for PSCR with O2 sensor data. This is probably a temporary arrangement because the way that libdivecomputer reads the Shearwater dive computer with only a single O2 sensor, which does not set the no_o2sensors in the correct way. Jef and myself are looking at this and this will probably change in the near future, removing the need to set no_o2sensors as it will be provided by libdivecomputer.

2018-03-05 13:02 UTC, glance- commented
I would like to see the two commits squashed into one, or even split into multiple different commits as a logical progression. Having them as these two different is more confusing than squashing them.

The odd no_o2sensors is still passed to fill_pressures(). Just pass the po2 instead, and the rest will just be correct.

Could you share a dive xml for ex. the dive above?

2018-03-05 18:55 UTC, willemferguson commented
Sample pscr dive attached as requested.

> 
[Sample_pscr_dive.xml.zip](https://github.com/Subsurface-divelog/subsurface/files/1782185/Sample_pscr_dive.xml.zip)

2018-03-05 20:32 UTC, glance- commented
I took a stab at it and I think it turned out pretty well:
https://github.com/glance-/subsurface/tree/pscr-fixes

That code completely drops the "re-use" of setpoint as "oc-equivalent-ppo2". I completely see how that can be relevant as a pscr diver, but I really don't like how its bolted on. Any case, it should be a separate patch.

That code doesn't handle the bailout event either. It should be quite easy to add. We don't have anything like it so it's really a separate thingie all along.

2018-03-06 04:47 UTC, willemferguson commented
Should I remove from this PR the code dealing with display of setpoint?
I would then submit an additional patch dealing with display of OC-pO2?
The next step after that would be to deal with bailout.
Does this seem like a logical progression?

2018-03-06 11:38 UTC, willemferguson commented
May I suggest the following?
1) You do a PR with your changes, above.
2) I will then create a new int variable as part of plot_info called OC_pO2 into which the OC equivalent pO2 (mbar) values will be stored. I will use this as a base for displaying this variable in the dive profile for PSCR dives with O2 monitoring.
3) After that one can worry about using markers for changing between bailout and the loop to adjust the dive for bailout. The provisions for bailout would probably also apply to CCR.
Would this make sense at all?

2018-03-06 19:23 UTC, glance- commented
No, no_o2sensors is infered in subsurface code from the number of DC_SAMPLE_PPO2 for a single DC_SAMPLE_TIME. I really don't get how you managed to get PPO2 samples, and no_o2sensors didn't get set.

Anyway, I'm happy with how the pscr code I wrote turned out, so if you're happy with it, I'll make a PR out of it.

2018-03-07 05:36 UTC, closed without merging