Debug: sprinkle debug messages in thumbnailing code
Subsurface-divelog/subsurface pull request #1180
Opened 2018-03-25 14:49 UTC by bstoeger

To ease trouble-shooting of the picture thumbnailer add a number
of debug- and info-messages.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation
- [x] Debugging

### Pull request long description:

Add debug-messages to the thumbnailing code to help troubleshooting #1179 

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2018-03-26 02:30 UTC, neolit123 requested changes
added a couple of small comments.

2018-03-26 02:30 UTC, neolit123 commented on core/imagedownloader.cpp
> +	if(url.isLocalFile()) {
might be a good opportunity to fix the missing space after `if`.

2018-03-26 02:30 UTC, neolit123 commented on core/imagedownloader.cpp
> +		qDebug() << "Translated filename: '" << picture->filename << "' --> '" << filename << "'";
probably better to use `arg()` here:
```
qDebug() << QStringLiteral("Translated filename: '%1' --> '%2'").arg(picture->filename).arg(filename);
```

2018-03-28 13:55 UTC, neolit123 commented on core/imagedownloader.cpp
> +		qDebug() << QStringLiteral("Translated filename: %1 -> %2'").arg(picture->filename, filename);
there is a stray `'`.

2018-03-28 13:56 UTC, neolit123 commented on core/imagedownloader.cpp
> +				qDebug() << "Loaded picture from translated filename " << filename;
i think the space after `filename` is not needed as each `<<` append is separated by space?

2018-03-28 13:57 UTC, neolit123 commented on core/imagedownloader.cpp
> +				qDebug() << "Loaded picture from translated filename " << filename;
applies to similar `qDebug()` calls?

2018-03-29 04:43 UTC, neolit123 commented on core/imagedownloader.cpp
> +		qDebug() << "Downloading image from " << url;
[1] sorry, my comment was about the extra space being redundant for all of these `qDebug()` calls.
```qDebug() << "Downloading image from" << url;```

2018-03-29 04:44 UTC, neolit123 commented on core/imagedownloader.cpp
> +		qDebug() << "Write image to " << imageFile.fileName();
[1]

2018-03-29 04:44 UTC, neolit123 commented on qt-models/divepicturemodel.cpp
> +		qDebug() << "No thumbnail in cache for " << entry.filename;
[1]

2018-03-30 12:37 UTC, neolit123 commented on qt-models/divepicturemodel.cpp
> +		qDebug() << "No thumbnail in cache for " << entry.filename;
```
qDebug() << "No thumbnail in cache for" << entry.filename;
```

2018-04-01 12:57 UTC, neolit123 approved these changes

2018-04-01 12:59 UTC, neolit123 commented
pushed a rebase to fix the remaining formatting issue on `qt-models/divepicturemodel.cpp:26`

2018-04-01 12:59 UTC, merged

2018-04-01 20:56 UTC, sfuchs79 commented
@neolit123 
I'm not 100% sure if it was @bstoeger intention to have this code in master ;-)
What I want to say: This code ALWAYS does produce a ton of debug messages as soon as you do something around dive pictures. Finally we may want to have s.th. like `#if DEBUG` around the debug code.
BTW: Maybe you could please once run the Windows build and do a test with adding a larger number of dive pictures to a dive? Sooner or later it would be very important to see if s.o. can reproduce my results from #1179

2018-04-01 21:21 UTC, neolit123 commented
@bstoeger @sfuchs79 
i trust you to fix this it if you think that there is way too much debug output.
we also support a flag for verbosity level.

2018-04-01 21:52 UTC, bstoeger commented
> The image data was invalid, and QImageReader was unable to read an image from it. The can happen if the image file is damaged.

I'm not sure myself. ;) It shouldn't produce too much output in release mode (`qDebug()` doesn't produce output for me). We can remove the redundant stuff once we fixed the problems.