Update user manual for CCR and pSCR dive logs
Subsurface-divelog/subsurface pull request #1277
Opened 2018-05-15 17:54 UTC by willemferguson

Update the text pertaining to CCR and pSCR dive logs to include the
changes with respect to:
1) Colour of CCR setpoint graph and pSCR OC-equivalen pO2 graph.
2) Display of bailout information on dive logs.
3) Preferences tab allowing setting pertaining to the above.

This is the first of a few PRs with updates to the user manual
relating to CCR and pSCR dives.

Signed-off-by: Willem Ferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x ] Documentation change
- [ ] Language translation

### Pull request long description:

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2018-05-15 23:41 UTC, neolit123 requested changes
thanks for the update.
copied the text changes into a word processor and found a couple of typos.

2018-05-15 23:41 UTC, neolit123 commented on Documentation/user-manual.txt
> +measured pO~2~ vaues are shown on the dive profile. In addition, the _Preferences_ panel allows one to activate
s/vaues/values/

2018-05-15 23:41 UTC, neolit123 commented on Documentation/user-manual.txt
> +more accurate not to record a bailout event in the dive log since _Subsurface_ will calulate pO~2~
`s/calulate/calculate`

2018-05-15 23:41 UTC, neolit123 commented on Documentation/user-manual.txt
> +More equipment-specific procdures and information for downloading CCR dive logs for
`s/procdures/procedures`

2018-05-17 14:30 UTC, dirkhh commented
@neolit123 this seems to address your concerns? Would you approve and merge?

2018-05-17 14:32 UTC, neolit123 commented
thanks, @willemferguson .

2018-05-17 14:32 UTC, merged