Various small fixes
Subsurface-divelog/subsurface pull request #1289
Opened 2018-05-17 20:06 UTC by atdotde

### Describe the pull request:

- [x Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Various smaller bug fixes

### Changes made:

1) Make sure we translate dive mode names and use the same strings in all places
2) Rename a variable to better reflect its meaning
3) Don't try to compute a total SAC when a cylinder was used where we don't have sane start and end pressures
4) Planner: Only store a set point for CCR segments

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:
 This is mainly a reaction to suggestions by @sfuchs79 and @willemferguson

2018-05-17 20:17 UTC, atdotde commented
Oops, we need to make sure, no translated values get written to the files. This needs updating. But not now. Will do this tomorrow.

2018-05-17 20:27 UTC, atdotde commented
OK, this wasn't that difficult.

2018-05-18 16:08 UTC, dirkhh reviewed
This works as is - I just wonder if we should avoid the double translation (and of course this turns into a divemode_text_ui[] after the last commit)

2018-05-18 16:08 UTC, dirkhh commented on profile-widget/profilewidget2.cpp
> +		action->setText(tr("Open circuit"));
why wouldn't we use divemode_text[OC] or something like this - otherwise we have the same string for translation multiple times...

2018-05-18 19:56 UTC, sfuchs79 commented
What is missing here compared to #1288:
- Change from "OC" to "Open circuit" in statistics.c and maintab.cpp
https://github.com/Subsurface-divelog/subsurface/pull/1288/files#diff-b2ac680bbcb4867dcc85c95b7171a13bR143
https://github.com/Subsurface-divelog/subsurface/pull/1288/files#diff-53425902966c23ff66293ccac9394931R112
- Translation for string "modechange"
https://github.com/Subsurface-divelog/subsurface/pull/1288/files#diff-75dcd3eb96f043b3dcbce84e1a0e8088R1615

2018-05-18 20:04 UTC, sfuchs79 requested changes

2018-05-18 20:04 UTC, sfuchs79 commented on desktop-widgets/diveplanner.cpp
> +		rebreather_modes.append(QString(divemode_text_ui[i]));
This imho this removes translation instead of adding it. `divemode_text_ui[i]` holds untranslated strings.

2018-05-18 20:04 UTC, sfuchs79 commented on profile-widget/diveeventitem.cpp
> +		name += tr(": %1").arg(divemode_text_ui[internalEvent->value]);
Doing `tr(": %1")` makes no sense to me. Not this string has to be translated but again the `divemode_text_ui` in the argument.

2018-05-18 20:04 UTC, sfuchs79 commented on profile-widget/profilewidget2.cpp
> +		if (QString(divemode_text_ui[i]) == action->text())
Careful here - isn't this now comparing a untranslated string with an translated string?

2018-05-20 19:48 UTC, dirkhh requested changes
This looks all good except for the commit message of the first commit... would you like me to clean that up for you or can you just fix that and force push?

2018-05-20 19:57 UTC, janiversen commented
I will fix it!

2018-05-20 20:01 UTC, janiversen commented
Sorry I was in the wrong PR :-)

2018-05-28 06:44 UTC, willemferguson commented
I propose that we accept the changes for merging.

2018-05-28 07:57 UTC, merged

2018-05-28 13:41 UTC, sfuchs79 commented
What about the open findings from my side? I don‘t think that was ready to be merged.

2018-05-28 15:45 UTC, atdotde commented
Sorry for not commenting earlier but I think these patches are correct, maybe except for the translation of the white space punctuation only string that was there before: the _ui string is the translated to be shown to the user and thus also to be compared to the action element.

2018-05-28 16:18 UTC, sfuchs79 commented
But the QT_TRANSLATE_NOOP doesn‘t realy translate the string. Its a NOOP as the Name says.

2018-05-28 18:39 UTC, dirkhh commented
The NOOP variation marks a string for translation, but at that spot in the code it stays untranslated. You can use that for example to initialize an array with the untranslated values while at the same time marking those strings for translation. You can then call tr() on the members of the array right as   you are about to display them, and since the strings were marked for translation they will be in the lookup table and will displayed in their translated form.

2018-05-28 18:48 UTC, sfuchs79 commented
@dirkhh 
Yes, that is exactly also my understanding.
But if I look at the code of this PR I can't see the "final" tr() call to actually do the translation. And also from @atdotde comments I think Robert wanted to have the strings translated already in the string list. But to achieve this the NOOP has to be changed to a real translate.

2018-05-28 18:55 UTC, dirkhh commented
So let's either revery this or maybe even easier, add another PR on top that fixes it.

2018-05-28 19:00 UTC, sfuchs79 commented
Double checking it with @atdotde and then fix it with another PR would be the better way.

2018-05-28 19:59 UTC, atdotde commented
Of course you are right. That should be translate instead of QT_TRANSLATE_NOOP. Do you want to do do a patch or shall I do it?