fix to qPrefCloudStorage git_url is derived from base_url
Subsurface-divelog/subsurface pull request #1540
Opened 2018-07-26 16:22 UTC by janiversen

### Describe the pull request:

- [ x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

old version of qPrefCloudStorage loaded/saved git_url from/to disk, whereas 
SettingsObjectWrapper derived git_url from base_url (kind of ugly, but)

Code changed to derive git_url from base_url,
test cases updated to test the relationship between base_url and git_url.

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:
·

### Mentions:

@dirkhh please test that all your multipke issues are solved
@sfuchs79 I am not sure this solves your case, so please test (I still fo not have a valid local profile).

2018-07-26 17:22 UTC, janiversen commented
the failure on travis qt59, looks like a travis update problem, not caused by this fix

2018-07-27 12:05 UTC, sfuchs79 commented
Result of very quick (5 seconds) test: Yes, fixes my issue. But will continue testing next week. I'm on the way to the airport...

2018-07-27 15:59 UTC, dirkhh requested changes
You left a few qDebugs in there...

2018-07-27 15:59 UTC, dirkhh commented on core/settings/qPrefCloudStorage.cpp
> +	qDebug() << " JAN load was called\n";
:-)
I do that all the time...

2018-07-27 15:59 UTC, dirkhh commented on core/settings/qPrefCloudStorage.cpp
> +
doesn't hurt, but I think once your messages are removed, we don't need it anymore

2018-07-27 15:59 UTC, dirkhh commented on core/settings/qPrefCloudStorage.cpp
> +
If any of these paths should be reported with '-v', then let's do that there (we do report the 'cloud URL' already)

2018-07-27 16:00 UTC, dirkhh commented
If you can't get to it today (I think you are working as DM again this week), let me know and I can edit your commits and remove the debug code... whatever works for you

2018-07-27 18:29 UTC, janiversen commented
Thanks for the suggestion, I just returned from a “deep” dive (AW) and a rescue course, so I need to relax with a bit of normal work.

Pushed an update, sorry for letting that slip.

2018-07-27 18:45 UTC, dirkhh commented
Where "_deep_" is what... 20m? :-)
I'll look at things over lunch (within the next hour or so)

2018-07-27 19:11 UTC, janiversen commented
30m (Padi regulation), max depth for padi advanced divers, hence the “”. But ok all beginnings are difficult, and the student was actually quite good.

2018-07-27 19:22 UTC, dirkhh approved these changes

2018-07-27 19:23 UTC, merged