Mobile: default cylinder
Subsurface-divelog/subsurface pull request #1594
Opened 2018-08-20 20:44 UTC by jbygdell

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
This PR adds the default cylinder functionality to subsurface mobile.

### Changes made:
1) Add an option to the settings page for the user to select a default cylinder.
2) Make the choice persistent by saving to disk via qPrefGeneral
3) If a default cylinder is defined select that when adding a new dive.

### Related issues:
Fixes #1535

### Additional information:

### Release note:
Add default cylinder functionality to Subsurface mobile.

### Documentation change:

### Mentions:

2018-08-20 20:44 UTC, jbygdell commented
derek add label: ui-mobile

2018-08-21 06:14 UTC, janiversen requested changes
the changes to qmlprefs, are bot really needed and only complicates the code, you can reference qPrefGeneral directly and use the signal from there.

2018-08-21 06:16 UTC, janiversen requested changes
If I apply only this commit mobile throws errors, due to e.g. when searching fir errors that each commit work as a unit.

2018-08-21 06:18 UTC, janiversen requested changes
do not call loadSync (and also not sync), use the qPrefGeneral vriable directly and the set method saves to disk.

2018-08-21 06:19 UTC, janiversen requested changes
why not use rebase to update the commit in question?

2018-08-21 11:33 UTC, janiversen commented
I forgot to write, you can make this change without changing C++, see tests/tst_qPrefGeneral for an example of how to use qPref directly.

2018-08-24 19:07 UTC, jbygdell commented
Rebased to match current master.

2018-08-24 19:17 UTC, janiversen commented
Your update looks good to me.

2018-08-24 19:20 UTC, jbygdell commented
@janiversen there is one thing that troubles me, the signal from qPrefs is never received on the QML side. In this case it is not a problem, but for other preferences it will be.

2018-08-24 19:43 UTC, janiversen commented
Thanks for noting this, I will add it to the test cases and see what is wrinh.

2018-08-25 14:01 UTC, dirkhh commented
This seems like a straight forward and very useful addition (the other discussion notwithstanding).
Thanks @jbygdell

2018-08-25 14:01 UTC, merged