[W.I.P] clean mobile-widgets and use qPref directly in cpp as well as qml
Subsurface-divelog/subsurface pull request #1661
Opened 2018-09-10 11:17 UTC by janiversen

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

With #1653 making qPref stable and available in C++ as well as QML, it is time to
starkly reduct qmlPrefs.cpp and qmlManager.cpp, who to a large extent serve as
a gateway between C++ and QML, but in a manner that are costly and do not allow signalling

qmlPrefs and qmlManager are available in QML as the C++ Class, meaning the objects will be
instanciated in QML (this is rather costly and memory consuming). qPref* are available directly
as C++ Object in QML and thus without any significant overhead.

The changes (especially around cloud credentials) are rather delicate, and needs a lot of manual testing, for that reason, each variable will be in a separate commit.

Remark: this PR is not concerned with how the qPref variables are used in the rest of the code, this is part of another discussion outside my scope.

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2018-09-10 11:46 UTC, janiversen commented
@dirkhh I need a bit of help in understanding the difference between
prefs.cloud_storage_email (which is used as userid on the git storage)
and
prefs.userid
they seem conflicting to me.

Secondly we have
prefs.cloud_storage_newpassword (which are not saved to disk)
that seems like a variable that should not exist ?

Ps. I am not doing any general cleanup, that I leave to others, but I am trying to reduce qmlprefs and qmlmanager, and for that reason I am confused.

2018-09-10 12:15 UTC, janmulder commented
I would worry to much about `prefs.userid`. This is (for as far as I know) only used for the GPS webservice thing, which is in the process to be deleted.

2018-09-10 12:16 UTC, janiversen commented
thanks that clears part of my confusion.

2018-09-10 13:39 UTC, dirkhh commented
And newpassword indeed shouldn't be in prefs - this is a case where it just seemed simple to keep it there - but that's of course bogus.

2018-09-10 14:05 UTC, janiversen commented
based on the feedback, I will remove userid and newpassword from mobile-widget (make the latter a class variable).

I will consider removing those 2 from qPref, if it can be done without effects outside mobile-widget and qPref.

I am currently untangling the whole mobile login process, which seems overly complicated (from a source code perspective)l

2018-09-10 14:44 UTC, dirkhh commented
I'm not sure how much time I'll have today, but I'll be happy to look into taking care of `newpassword` and `git_local`

2018-09-12 13:56 UTC, janiversen commented
Thanks I was not aware of this, you can hold back this PR if you like, and I will amend to it (was preparing for a second PR)

2018-09-12 14:07 UTC, dirkhh commented
This all depends on how confident you are that you didn't break anything, doesn't it? :-)
Seriously, I don't see a point in slowing you down as you improve the code, I just don't want to end up breaking things right before cutting releases.

2018-09-12 14:12 UTC, dirkhh requested changes
I **really** like the granularity of these changes.
Easy to understand, should be easy to test as well.
Let's not leave the log message in there, also a couple of questions.

2018-09-12 14:12 UTC, dirkhh commented on mobile-widgets/qml/Settings.qml
> +					console.log("JAN changed developer menu(" + PrefDisplay.show_developer + ")")
Entertaining to have in the log, but maybe not in production code :-)

2018-09-12 14:12 UTC, dirkhh commented on core/gpslocation.cpp
> +	connect(qPrefLocationService::instance(), SIGNAL(qPrefLocationService::time_thresholdChanged()), this, SLOT(setGpsTimeThreshold(int seconds)));
the code doesn't seem to match the commit message. Yes, you now listen to a signal, but where is the "do not call" part?
Or am I misunderstanding the commit message?

2018-09-12 14:12 UTC, dirkhh commented on mobile-widgets/qml/Settings.qml
> +					PrefLocationService.time_threshold = timeThreshold.text * 60
not criticism, just curious... why did this change between minutes and seconds?

2018-09-12 14:36 UTC, janiversen commented
Please have a look at the new commit messages and see if they are more descriptive.

Regarding the "how confident I am", I have tested every commit by:
1) start app, change the value en question
2) restart app, and secure value is actually changed

For the part changed in this PR, I could not see much more testing. Whereas future changes like e.g. the whole cloud identification needs much more testing.

2018-09-12 21:45 UTC, janiversen commented
@dirkhh  Seems I hit a snag again, I believed #1097 was dead but to be sure and not step on toes, I. asked and to my surprise got the answer, that it is still valid.

Seems whatever I work on gets blocked, which is anything but motivating. My qPref work was blocked by a PR that seems not to be moving, now my mobile-widget work is blocked by a longterm project, that haven't been touched since February.

I am just happy, I checked that PR, before I invested too much time. I honestly thought that I had proven myself in the area of C++ / QML or detangling IO and UI.

I am (or more correctly was until 1 hour ago) working on detangling the whole CloudCred process, which (pardon me) is a big mess, with several illogical user situations (just one example: try to have a verified cred, then change your password to a faulty one...what happens you get the old divelist, until you restart the ap).

I have no intention of repeating the qPref disaster (for me), then better do something else !

2018-09-12 23:11 UTC, dirkhh commented
I think your qPref work is moving and continues to move - we still want to move to making prefs constant, but it seems much more that that work is currently on hold because of the changes you had made.
Frankly, I thought the majority of the qPref work (as far as C++ changes) was done and what was left was qmlmanager/QML code updates. Please let me know what I'm obviously missing.

To be honest, I don't quite understand how you pick the areas that you work on. So all that pref work was ostensibly so that you could make significant updates to the QML UI. I don't see how the cloud credentials can be a blocking item for that. I appreciate that you see code that you don't like and want to change it, but I also see that you dislike fundamentally all of the existing code. And the incremental value of you reimplementing all of the existing code differently is not entirely clear to me. Again, maybe I'm missing something obvious.

2018-09-13 03:06 UTC, dirkhh approved these changes

2018-09-13 03:23 UTC, closed without merging

2018-09-13 05:51 UTC, janiversen commented
qPref is closed from my side....I have what I need for QML and somebody will surely implement the missing parts in the rest of the system uding this strange const thing.

It is not true that I dislike all code far from, I concentrated on qPref to make a stable platform for QML, and it was natural to integrate qPref in the rest of the system, which probably was my mistake.

Now I have climbed the ladder, to demangle qmlmanager/qmlpref or more correctly to simplify. That part will change a lot of QML (and not just renaming). qPref is no blocker at all, but seeing somebody else have a long term project running to make this happen, makes me carefull not to make work for nothing again (I have thrown away quite a number of prepared qPref integration in the rest, due to the const decision).

CloudCred is basically blocked because I thought I was the only one working on detangling the mobile UI - IO, but now I know I am not. In contrary to the other, I keep my number of open PR´s and themes at 1, and I quickly finalize things....having a PR not being touched since february is to me a really loooong term project.