Improve OTU calculations
Subsurface-divelog/subsurface pull request #1865
Opened 2018-11-21 16:57 UTC by atdotde

This is #1851 that now applies to current master.

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2018-11-21 18:30 UTC, dirkhh requested changes
Please look at the CHANGELOG and reconsider if this is what you REALLY want...

2018-11-21 21:55 UTC, atdotde commented
Oops, thanks for noting this. Also removed two trailing white spaces.

2018-11-21 21:59 UTC, dirkhh approved these changes

2018-11-22 00:37 UTC, neolit123 approved these changes
thanks @atdotde 
i saw the paper and i don't understand how eq2 was factored, but you are trusted on this! :)

2018-11-22 00:37 UTC, merged