Remove default stylesheet from planner output
Subsurface-divelog/subsurface pull request #209
Opened 2017-02-17 07:45 UTC by sfuchs79

Remove the default stylesheet ("Courier" 13pt) from the planner output QTextEdit.

Fix for #203
S.o. with experience should please review this. But I think this goes into the right direction.

Advantages:
Display is according to font settings.
ctrl - mousewheel for zoom works.
Drawbacks/bugs:
Printing font is same as display font but can be adjusted by zooming before.
After once printing ctrl-mousewheel is disabled.

Signed-off-by: Stefan Fuchs <sfuchs@gmx.de>

2017-02-18 18:53 UTC, dirkhh requested changes

2017-02-18 18:53 UTC, dirkhh commented on desktop-widgets/plannerDetails.ui
> +&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;&quot;&gt;
I don't think it makes sense for us to refer to a proprietary font here, so let's keep it Courier (and wouldn't you want a fixed width font here, anyway?) - and the way I read this, you are just hard coding a smaller size. What am I missing?

2017-02-18 18:53 UTC, dirkhh commented on desktop-widgets/mainwindow.cpp
> +	plannerDetails()->divePlanOutput()->setHtml(displayed_dive.notes);
why are you making this change? I don't see this explained anywhere.

2017-02-18 18:53 UTC, dirkhh commented on desktop-widgets/plannerDetails.ui
> +      <string notr="true"/>
This seems to be the only change that is actually covered in the commit message

2017-02-20 08:53 UTC, sfuchs79 commented
Let's try to explain this with more details:
First about the font: I don't think we need Courier or another fixed width font here. We use a html table for the runtime. And looking at the result on both Windows (10) and Linux I tend to say that using the standard font of the tool (or even system) looks nicer. For Windows 10 and my display for example this would be Segeo UI 8.25pt. On my Ubuntu with another display the default is DejaVu Sans 11pt. This also looks nice for both display and printing. In comparison to this IMHO Courier 13pt looks ugly for display both on Windows and Linux.

Then about the changes:
I carefully read again how QTextEdit works. This is important for us:
- We use the QTextEdit in "readonly" mode and put our text there with the "setHtml" function. This means it is not relevant at all what we put in the "html" property of the ui file. This will be overwritten with every setHtml we do. So we even could keep the "html" property empty. I tested this and can update the pull request accordingly. There was s.th. before in the "html" property only because Qt Creator puts there s.th. by default.
- We update the planner output with ...setHtml(displayed_dive.notes) every time the result string is updated. The string in displayed_dive.notes is text with simple html markup like line breaks, the table, a little bit of text color. But the string has NO font or font size info. If we now have NO default style sheet for the QTextEdit the text with simple markup will go to the QTextEdit and Qt applies the default font and font size. Plus the fact that ctrl-mousewheel will be enabled for zoom in/out. This will not work if we have a default style sheet because then the text will be always formated according to this style sheet.
- No about printing: Printing is maybe implemented in a little bit hacky way but it works fine. We first copy the content from the QTextEdit to a string with the function "toHtml". What is very important now: What we get from "toHmtl" is not the same as what we had in displayed_dive.notes before. Because this now has additional markup for example including font and current font size (based on zoom level!). We now add picture, icon and disclaimer and put it back with "setHtml". Then we print it. What is nice now is that the selected font size from zooming with ctrl-mousewheel in also applied to the printout.
- Last step after printing - and this is the other undocumented change by me: We now must not put back the string we got via "toHtml" again by using the function "setHtml". This would disable zoom again. We simply should copy back displayed_dive.notes once again and we will have the same result and status as before printing.

So hopefully no mistake in what I wrote. Maybe again it would be better if anyone with Qt experience has a look on this.

Btw: An additional (+) and (-) button for zoom close to the print button would be also a nice feature. Ctrl-mousewheel function may not be obvious to everyone. I may do this later :-)

2017-02-20 12:22 UTC, dirkhh commented
You don't address my question about the Ubuntu font - if you want a non-fixed-width font, use "sans-serif"

2017-02-20 12:34 UTC, sfuchs79 commented
Pushed an update. There is no need for specifying any font. Not the Ubuntu font and also no other. Default font from Subsurface settings will be used.

2017-02-20 17:42 UTC, merged