[RFC] Dive merge: don't use unset dive numbers
Subsurface-divelog/subsurface pull request #2133
Opened 2019-06-23 19:42 UTC by bstoeger

On merging, don't use the number of the first dive if it is 0.
Use the first non-zero number.

Fixes #2126

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Use the first non-0 number when merging dives.

### Release note:

Maybe?

### Documentation change:

No.
### Mentions:

@mturkia @dirkhh

2019-06-23 20:00 UTC, dirkhh approved these changes
I'd like it better without the `auto`, but it seems fine

2019-06-23 20:57 UTC, bstoeger commented
OK - will replace by classical loop tomorrow.

2019-06-24 08:21 UTC, dirkhh requested changes

2019-06-24 08:21 UTC, dirkhh commented on desktop-widgets/command_divelist.cpp
> +			d->number = d->number;
that does seem a bit too tautological... I think you meant `d->number = dive->number`...

2019-06-24 08:54 UTC, dirkhh approved these changes
that looks right

2019-06-24 21:34 UTC, dirkhh commented
So this passes tests, code looks great - why is this an RFC? 
OK, let's comment: I think it makes sense when merging dives to generally pick the earlier number (think merging your last two dives), but only pick a valid number...

2019-06-25 13:22 UTC, bstoeger commented
In the `merge_dives()` core-function we determine the *largest* number. Since the code sends different messages, I thought it was prudent to get opinions. Taking the first (non-zero) number appears more logical to me.

2019-06-25 13:39 UTC, mturkia commented
I think of two slightly different use cases (most common ones)
- 0 and non-zero dive numbers, and that merge should obviously be non-zero
- two numbered dives: this case would logically warrant for the smaller number. In case we are merging the latest two dives, this will keep the dives numbered without gaps.

What is the first non-zero? How are the dives ordered?


> On 25 Jun 2019, at 16.22, bstoeger <notifications@github.com> wrote:
> 
> In the merge_dives() core-function we determine the largest number. Since the code sends different messages, I thought it was prudent to get opinions. Taking the first (non-zero) number appears more logical to me.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-06-28 11:22 UTC, dirkhh commented
I'll merge as is as I now twice ran into a case that this code would have fixed.
If we want to fine tune the logic later, that's ok with me.

2019-06-28 11:23 UTC, merged