(qmlpref 2) clean saveCredentials / verifyCredentials use in QML
Subsurface-divelog/subsurface pull request #2489
Opened 2019-12-27 13:11 UTC by janiversen

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Made the login process boil down to 1 function call:
saveCredentials(<email>, <password>, <pin>)
seen from QML.

Apart from making the interface simpler it also reduces the use of qmlprefs in qmlmanager.

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2019-12-27 19:00 UTC, dirkhh requested changes
Please refactor those commits as indicated in the comment.

2019-12-27 19:21 UTC, janiversen commented on mobile-widgets/qml/CloudCredentials.qml
> +					manager.saveCloudCredentials(login.text, password.text, "")
Agreed, only excuse it that between the 2 commit was a lunch break. Corrected.

2019-12-27 21:54 UTC, dirkhh approved these changes

2019-12-28 16:09 UTC, dirkhh approved these changes

2019-12-28 16:41 UTC, dirkhh commented
manually merged

2019-12-28 16:41 UTC, closed without merging