Fix/uemis retry resuming download without retry button
Subsurface-divelog/subsurface pull request #3388
Opened 2022-02-10 19:02 UTC by Schwaneberg

### Describe the pull request:

- [X] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Is PR is a possible fix to issue #3385 .
There is a prompt to reconnect the Uemis from the status bar. Not a very elegant solution, but an easy solution for uemis downloader (which is written in C). I have an Uemis Zürich in excellent condition and tested the code with it.
I also added support for an environment variable to define an offset to start downloading from.

I know that this patch isn't very high quality. I'd rather suggest to re-implement the Uemis Zürich downloader from scratch in modern C++, if it wasn't for such an old legacy device. I just hope that you accept this small change to help the (few?) remaining Uemis users to elongate the useful lifespan of the remaining devices.

### Changes made:
1) Replaced "goto bail" with a prompt to reconnect the dive computer, if the synchronization memory is almost full.
2) Automatic termination, reset of filenr and re-initialization after a 60s timeout.
3) Reading an env variable UEMIS_DIVE_OFFSET, which can be used to modify the  start index for the (very slow) indexing process.

### Related issues:

#3385 

### Additional information:

### Release note:
Support synchronization over multiple reconnects with Uemis Zürich.

### Documentation change:
As you can see below, I added some lines to the documentation to provide some explanation for the use of the optional env variable.

### Mentions:
@dirkhh

2022-02-10 19:33 UTC, dirkhh requested changes
I have a few comments that are worth a conversation, and a few things that just really should be changed.

2022-02-10 19:33 UTC, dirkhh commented on core/uemis-downloader.c
> +				char msg[strlen(translate("gettextFromC", ERR_FS_ALMOST_FULL)) + 4];
so `translate(context, text)` returns a `const char *` into the `translationCache`.
Because of that this code is not quite as bad as it looks at first glance, but still... ugh. That's pretty darn wasteful.
Why not
```
const char *errormsg = translate("gettextFromC", ERR_FS_ALMOST_FULL);
char msg[strlen(errormsg) + 4];
```
and then use `errormsg` in the `sprintf()` call below.
I realize that I'm old... variable sized arrays have been around since C99 / C++14 and I still would have instinctively written this as a `malloc()` - even though this makes memory management easier on the code...

2022-02-10 19:33 UTC, dirkhh commented on core/uemis-downloader.c
> +					usleep(1000000);
wait, what? Why are you doing this busy loop? A 60s countdown in the status messages? With no way to interrupt?
Yeah, not a fan. Not at all a fan.
Also... did you take a look at the definition of `uemis_info()`? That already takes `printf()` style arguments, so that whole `sprintf()` and the whole thing with the `msg` buffer I commented on above is not needed in the first place.

But before we focus on that simplification... why the busy loop here? How does that help?

2022-02-10 19:33 UTC, dirkhh commented on core/uemis-downloader.c
>  					uemis_info(msg);
that part should have been squashed with the previous commit

2022-02-10 19:33 UTC, dirkhh commented on core/uemis-downloader.c
> -
and that should be explained in the commit message...

2022-02-10 19:33 UTC, dirkhh commented on core/uemis-downloader.c
> +	start += dive_offset;
what does the algorithm do with a negative offset? I mean, sure, garbage in, garbage out... but maybe the code should require this to be `>= 0` ?

2022-02-10 19:33 UTC, dirkhh commented on core/uemis-downloader.c
> +				param_buff[1] = "notempty";
shouldn't the commit message (or even better, some comments here) explain what this is doing?

2022-02-10 20:25 UTC, Schwaneberg commented on core/uemis-downloader.c
> +				char msg[strlen(translate("gettextFromC", ERR_FS_ALMOST_FULL)) + 4];
Ok. BTW: I doubt that the shortened message "Disconnect/reconnect the SDA" requires any translation at all.
It must be short to fit in the progress bar.

2022-02-10 20:26 UTC, Schwaneberg commented on core/uemis-downloader.c
> +					usleep(1000000);
It really like to use a QMessageBox dialog here, but it is pure C...

2022-02-10 20:44 UTC, Schwaneberg commented on core/uemis-downloader.c
> +				param_buff[1] = "notempty";
This is just a partial initialization - just as above the for (;;) loop. I could have refactored the code and put this into a new function for reuser, but instead I implemented a check to compare the device id.

2022-02-10 22:09 UTC, dirkhh commented on core/uemis-downloader.c
> +					usleep(1000000);
yeah - that would be through a callback. We use that mechanism in other places.
This really isn't a solution. This isn't even a decent hack 😂

2022-02-10 22:11 UTC, dirkhh commented on core/uemis-downloader.c
> +					filenr = 0;
remind me - why are you setting `filenr` to 0 sixty-one times in a row?

2022-02-10 22:12 UTC, dirkhh commented on core/uemis-downloader.c
>  				filenr = 0;
and then one more time, just to be sure? 😁

2022-02-14 19:12 UTC, Schwaneberg commented on core/uemis-downloader.c
> -
I can revert this, but it shouldn't even happen anymore.

2022-02-14 21:20 UTC, dirkhh commented
ok, I think this makes sense... I'll refactor the commits locally and create a new branch from that so we can run our CI/CD against the cleaned up version.

2022-02-15 17:32 UTC, dirkhh commented
closing this since #3393 was merged

2022-02-15 17:32 UTC, closed without merging