desktop: set composition flag in dive site list
Subsurface-divelog/subsurface pull request #3487
Opened 2022-08-13 18:29 UTC by bstoeger

This is crazy: when view() is called, the dive-site-suggestion
popup (DiveLocationListView) clears its WA_InputMethodEnabled
flag. This makes key composition not work as long as the
popup is open.

Thus, when showing the popup, explicitly set the flag.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This fixes composition in the dive-site field on the main tab. For some reason the dive site list clears its composition enabled flag, when show() is called. Extremely weird, but there must be some good reason. For now, just set it explicitly.

Contains a few coding-style fixes.

2022-08-13 18:36 UTC, dirkhh requested changes
please strip the libdivecomputer change from this branch

2022-08-13 21:11 UTC, dirkhh approved these changes
This seems otherwise similar to what you did in the previous one. So should I merge this?
Or (given that you are likely asleep) - feel free to merge when you have time

2022-08-14 07:57 UTC, bstoeger commented
Ok, I think I found the culprit:
In https://github.com/qt/qtbase/blob/dev/src/widgets/itemviews/qabstractitemview.cpp when current is set to an item that is not "editable" composition is turned off:

```
setAttribute(Qt::WA_InputMethodEnabled, (current.isValid() && (current.flags() & Qt::ItemIsEditable)));
```

This means that all items must be marked as editable.

Usually I quite like QtWidgets (in stark constrast to QtCore or QtQuick!), but this just feels very messy!

PS: I'll be gone for two weeks now.

2022-08-16 00:51 UTC, thiagomacieira commented
Following up from #3486 - I have no clue what these flags do. I could guess who to ask for instruction, but can I ask for a concise description of what the problem is?

2022-08-16 05:30 UTC, bstoeger commented
Only widgets with the `Qt::WA_InputMethodEnabled` flag get `inputMethodEvent()` calls. These are necessary for composing characters from multiple key strokes, such as the East Asian languages do. However, apparently also some users of European languages use that input method.

The `TagWidget` and `DiveLocationLineEdit` widgets show auto-completers in the form of `QListView`s. To enable editing while the auto-completion popup is shown, the events received by the `QListView` are forwarded to the widget by event filters. However, if the `ItemIsEditable` flag is not set, the `QListView` clears the `Qt::WA_InputMethodEnabled` flag and thus breaks key composition. See the line I quoted above.

Thanks.

2022-08-18 04:41 UTC, bstoeger commented
The problem is: how do we prevent the loss of `inputMethodEvent()` calls while the auto-completion popup is opened?

2022-08-21 09:47 UTC, bstoeger commented
If we don't get an answer in due course, I suggest merging this. It is surely wrong and ugly, but it does (hopefully) fix a very significant UI problem.

2022-08-22 01:55 UTC, dirkhh approved these changes
I think this is good to merge, Berthold?

2022-08-22 09:32 UTC, bstoeger commented
Well - up to you. Do you want to wait for an authoritative answer, or just say "whatever, let's move on"?

2022-08-22 16:20 UTC, dirkhh commented
hehe... whatever... just move on.

2022-08-22 16:20 UTC, merged