Fixes stray diveguide references in HTML export
Subsurface-divelog/subsurface pull request #3571
Opened 2023-01-05 07:54 UTC by AVGP

In translations, it's still `diveguide`, but elsewhere the property is called `divemaster`. This broke search in the HTML export.

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
I noticed that the search in the HTML export was broken, so I looked into it.
Turns out that the previous change to this file renamed the `diveguide` property in the dives to `divemaster` but didn't catch all the references to it. This PR fixes the remaining references and, thus, the search feature.

### Changes made:
1. renamed remaining `diveguide` property references to `divemaster`.
2. fixed search feature

### Related issues:

### Additional information:

### Release note:
Fixes search functionality in the HTML export

### Documentation change:

### Mentions:

2023-01-05 16:05 UTC, dirkhh requested changes
the goal is actually to go the other direction. So we need to change the export function to write this as `diveguide` instead of `divemaster`, not revert back to the old term that we want to move away from.

2023-01-06 17:58 UTC, AVGP commented
Whoops, sorry @dirkhh - fixed it into `diveguide` as needed.

2023-01-06 18:16 UTC, dirkhh commented
> Whoops, sorry @dirkhh - fixed it into `diveguide` as needed.

Now if I merge this locally and do a diff against the previous version, the only thing that changes is the CHANGELOG... so I think this may still be missing something 🤔
(you can replicate this here by looking at https://github.com/subsurface/subsurface/pull/3571/files - which I should have done before merging, I guess...)

2023-01-06 18:20 UTC, AVGP commented
Hm, I'll take a look soon when I'm not as tired anymore.

2023-01-12 11:27 UTC, AVGP commented
Alright, with a bit of sleep, I figured it was the `dive_export.html` not the js file where the references appeared. This includes a UI label. Fixed now :)

2023-01-12 13:14 UTC, atdotde commented
I know nothing about this part of the coffee, but why not search_item_diveguide for consistency?

2023-01-12 13:44 UTC, AVGP commented
@atdotde Good question. I dunno what the conventions are neither did I check. I just replaced `divemaster` with `diveguide` to fix the issue. But being a good scout, I'll change the name of the HTML element and the JS lookup code to follow the conventions.

2023-01-12 13:46 UTC, atdotde commented
:-)

BTW did you get my message on mastodon?

2023-01-13 06:20 UTC, AVGP commented
> :-)
> 
> BTW did you get my message on mastodon?

I did indeed and I'll reach out to you separately to figure out how to get you on the podcast :)

2023-01-19 14:57 UTC, dirkhh commented
merged #3574

2023-01-19 14:57 UTC, closed without merging