Convert README to markdown and add Travis CI build status, closes #765
Subsurface-divelog/subsurface pull request #766
Opened 2017-11-04 00:03 UTC by probonopd

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Documentation change
- [ ] Language translation

### Pull request long description:
Convert `README` file to markdown and add Travis CI build status. Fixes #765

2017-11-04 13:25 UTC, neolit123 requested changes
only a couple of whitespace changes requested.
but i will leave this to @dirkhh.

personally i don't mind this. it makes the repo more 'modern'.

2017-11-04 13:25 UTC, neolit123 commented on README.md
> +
stray whitespace

2017-11-04 13:25 UTC, neolit123 commented on README.md
> +
more bellow.

2017-11-04 14:20 UTC, probonopd commented on README.md
> +
Should be addressed in the meantime.

2017-11-04 14:20 UTC, probonopd reviewed
Please check latest commit.

2017-11-04 15:35 UTC, dirkhh commented
I like it. Thanks @probonopd

2017-11-04 15:35 UTC, merged

2017-11-04 16:42 UTC, sfuchs79 commented
After renaming the README to README.md we need to change the file name also in some makefiles and maybe some other places. Recognized this because currently creating the Windows NSI installer fails because of this.

CMake Error at cmake_install.cmake:51 (file):
  file INSTALL cannot find
  "/home/stefan/Entwicklung/Subsurface/subsurface/README".

2017-11-04 16:43 UTC, probonopd commented
Uh, sorry @sfuchs79 for having broken this. I am not a Windows user, so would appreciate if you could fix it.

2017-11-04 16:53 UTC, sfuchs79 commented
I guess this is not a pure Windows thing because the README file is also mentioned in a script and some other file :-)
I'll try to catch all occurrences and sent a PR but @dirkhh has to review this carefully.

2017-11-04 17:25 UTC, sfuchs79 commented
-> #772

2017-11-04 17:54 UTC, dirkhh commented
One of the things we SHOULD do is get Travis to also build a Windows installer...
I had started working on doing a Mac build on Travis when they started to offer that option but never got it to work and frankly gave up - but this would be really cool to have.
Not sure if you'd be interested to experiment with that, @sfuchs79

2017-11-04 19:44 UTC, sfuchs79 commented
@dirkhh 
I for sure agree that this would be very nice.
But the best thing I can offer at the moment is that I put it at the bottom of my Subsurface OIL. And this list is pretty long at the moment.
One small thing I can offer immediately: If you create an issue for this I can add there s.th. nice I found on the web: MXE is providing some instructions and an example project for MXE Travis integration.

2017-11-05 00:11 UTC, dirkhh commented
-> #775